scene.setBackgroundImage(img`
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    dddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeee
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    eeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddddeeeeeeeeeeeeeeddddddddddddd
    `)
let BlackPawn1 = sprites.create(assets.image`myImage0`, SpriteKind.Player)
BlackPawn1.setPosition(7, 22)
let BlackPawn2 = sprites.create(assets.image`myImage3`, SpriteKind.Player)
BlackPawn2.setPosition(22, 22)
let BlackPawn3 = sprites.create(assets.image`myImage4`, SpriteKind.Player)
BlackPawn3.setPosition(36, 22)
let BlackPawn4 = sprites.create(assets.image`myImage5`, SpriteKind.Player)
BlackPawn4.setPosition(50, 22)
let BlackPawn5 = sprites.create(assets.image`myImage6`, SpriteKind.Player)
BlackPawn5.setPosition(64, 22)
let BlackPawn6 = sprites.create(assets.image`myImage7`, SpriteKind.Player)
BlackPawn6.setPosition(78, 22)
let BlackPawn7 = sprites.create(assets.image`myImage1`, SpriteKind.Player)
BlackPawn7.setPosition(92, 22)
let BlackPawn8 = sprites.create(assets.image`myImage0`, SpriteKind.Player)
BlackPawn8.setPosition(106, 22)
let WhitePawn1 = sprites.create(assets.image`myImage8`, SpriteKind.Player)
WhitePawn1.setPosition(7, 92)
let WhitePawn2 = sprites.create(assets.image`myImage9`, SpriteKind.Player)
WhitePawn2.setPosition(22, 92)
let WhitePawn3 = sprites.create(assets.image`myImage10`, SpriteKind.Player)
WhitePawn3.setPosition(36, 92)
let WhitePawn4 = sprites.create(assets.image`myImage11`, SpriteKind.Player)
WhitePawn4.setPosition(50, 92)
let WhitePawn5 = sprites.create(assets.image`myImage12`, SpriteKind.Player)
WhitePawn5.setPosition(64, 92)
let WhitePawn6 = sprites.create(assets.image`myImage13`, SpriteKind.Player)
WhitePawn6.setPosition(78, 92)
let WhitePawn7 = sprites.create(assets.image`myImage14`, SpriteKind.Player)
WhitePawn7.setPosition(92, 92)
let WhitePawn8 = sprites.create(assets.image`myImage15`, SpriteKind.Player)
WhitePawn8.setPosition(106, 92)
let WhiteKnight1 = sprites.create(assets.image`myImage30`, SpriteKind.Player)
WhiteKnight1.setPosition(92, 106)
let WhiteKnight2 = sprites.create(assets.image`myImage31`, SpriteKind.Player)
WhiteKnight2.setPosition(22, 106)
